#!/usr/bin/python -tt
# by skvidal
# gplv2+

import sys
import func.overlord.client
from func.overlord.scripts import base_func_parser, handle_base_func_options, errorprint
from func.utils import is_error


def main(args):
    parser = base_func_parser(outputpath=False, timeoutdef=10)
    opts, args = parser.parse_args(args)
    opts = handle_base_func_options(parser, opts)


    hosts ='*'
    if opts.host:
        hosts = ';'.join(opts.host)

    fc = func.overlord.client.Client(hosts, timeout=opts.timeout, nforks=opts.forks)

    results = fc.test.ping()
    offline = []
    for (hn, out) in results.items():
        if out != 1:
            offline.append(hn)

    print '\n'.join(sorted(offline))

    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))


