#!/usr/bin/python -tt
# by skvidal
# gplv2+


import sys
import func.overlord.client
from func.overlord.scripts import base_func_parser, handle_base_func_options, errorprint
from func.utils import is_error


def main(args):
    parser = base_func_parser(outputpath=False)
    parser.add_option('--returncodes', action='store_true', help="prefix each line with the commands returncode")
    parser.add_option('--oneline', action='store_true', help="output all things as one line - to make grepping easier, will not remove \n's from output of commands, though")
    opts, args, parser = parse_args(args)
    opts = handle_base_func_options(parser, opts)

    if len(args) < 1:
        errorprint(parser.format_help())
        return 1

    mycmd = ' '.join(args)

    hosts ='*'
    if opts.host:
        hosts = ';'.join(opts.host)

    fc = func.overlord.client.Client(hosts, timeout=opts.timeout, nforks=opts.forks)

    print mycmd
    results = fc.command.run(mycmd)
    for (hn, output) in results.items():
        if is_error(output):
            msg = 'Error: %s: ' % hn
            for item in output[1:3]:
                if type(item) == type(''):
                    msg += ' %s' % item
            errorprint(msg)
            continue

        if opts.oneline:
            if opts.returncodes:
                print '%s:%s:%s' % (hn, output[0], output[1])
            else:
                print '%s:%s' % (hn, output[1])
        else:
            if opts.returncodes:
                print '%s:\nreturn code:%s\n%s' % (hn, output[0], output[1])
            else:
                print '%s:\n%s' % (hn, output[1])

    
if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
